### ISSUE TITLE
The code is crashing on plot

### ISSUE THREAD

**Issue by dfm** [davidwhogg/TheThresher#28]
Here's the `Exception`:

``` bash
Traceback (most recent call last):
  File "code/lucky.py", line 569, in <module>
    plot=plot, splot=splot)
  File "code/lucky.py", line 264, in inference_step
    stretch=3.)
  File "code/lucky.py", line 323, in plot_inference_step
    hogg_savefig(filename)
  File "code/lucky.py", line 334, in hogg_savefig
    return plt.savefig(fn)
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 471, in savefig
    return fig.savefig(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/figure.py", line 1185, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 2021, in print_figure
    **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.py", line 469, in print_png
    FigureCanvasAgg.draw(self)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.py", line 421, in draw
    self.figure.draw(self.renderer)
  File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/figure.py", line 898, in draw
    func(*args)
  File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 1997, in draw
    a.draw(renderer)
  File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/image.py", line 350, in draw
    im = self.make_image(renderer.get_image_magnification())
  File "/usr/lib/pymodules/python2.7/matplotlib/image.py", line 569, in make_image
    transformed_viewLim)
  File "/usr/lib/pymodules/python2.7/matplotlib/image.py", line 201, in _get_unsampled_image
    x = self.to_rgba(self._A, bytes=True)
  File "/usr/lib/pymodules/python2.7/matplotlib/cm.py", line 213, in to_rgba
    x = self.norm(x)
  File "/usr/lib/pymodules/python2.7/matplotlib/colors.py", line 850, in __call__
    raise ValueError("minvalue must be less than or equal to maxvalue")
ValueError: minvalue must be less than or equal to maxvalue
```

**Comment by davidwhogg** [comment]
we need to fork off the plotting.

**Comment by dfm** [comment]
done and done

**Comment by dfm** [comment]
I closed this prematurely...

The plotting code is forked but I forgot that it still crashes. And it doesn't have anything to do with the stretch.

For the record, I think that it crashes on: `tmp-q_e_20120416_34_1_1_0_01764.fits`

**Comment by davidwhogg** [comment]
meaning; even if we run the system on JUST that image, it STILL crashes?  That's f*@ked.

**Comment by dfm** [comment]
Fixed.
